name: slimhub_actions Check on MacOS 11

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: macos-11.0

    env:
      # Change These If You Are Forking The Repo
      GitHubMail: "rokibhasansagar2014@outlook.com"
      GitHubName: "rokibhasansagar"

    steps:
    - name: Set Git Configs & Secrets
      run: |
        git config --global user.email ${GitHubMail}
        git config --global user.name ${GitHubName}
        git config --global color.ui true
        git config --global credential.helper store
        echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
    - name: System Specs
      run: system_profiler SPHardwareDataType
    - name: Cleanups
      uses: rokibhasansagar/slimhub_actions@mac
