name: WindowsCI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Ngrok
        run: choco install ngrok.portable
      - name: Firewall
        run: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
      - name: Auth
        run: ngrok authtoken $Env:NGROK_TOKEN
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

      - name: Shell test
        run: |
          df -hlT || true
          ls -lA . || true
          which ngrok
          ngrok help
        shell: bash

      - name: Create Tunnel
        shell: bash
        run: |
          ngrok tcp 22 || true
          echo "Dummy"
