name: WindowsCI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Firewall
        run: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

      - name: Create Tunnel
        shell: bash
        run: |
          printenv | sort
          ssh-keygen -R $hostname
          ssh -R 80:localhost:8080 localhost.run
